language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - iojs-v1
  - iojs-v2
script: npm test
before_script:
  - npm install
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
env:
  global:
    - secure: i1pENwoJlg0NEyl42AYoOcC6fqA//3FXpLjsaIxx5U1485ikz7KuZ6ejYHmvbQxu1HSy+E4dgri9nUZSexrwyDU4ZB3uc9RjI+BkDerJaa9uWqjLUdPEDgkqGayJc5rhz25u7ykND4EOYoU9Q2vqgjqj7hJxmEzW5g/VStsUcV0BP8Xef2WJ4ubt3+8/f9/EZYBugr5LV0STp/a3A52/QyV+Td8+/TsUiReidFlUCiXB+6IVMRxdLX380iWvs2AKcIntW5MTFh6EyUGqUjXfJTZUUZibOsT+QwMEntKl7jydWPIxcwB+MSqYUBgreivvpN75MZbUfT919FoOQAKqndv9nNOFIPq+7vGiraxzgaHcbY/oSI1mkA+OhG0JW3gQXhvjDlPpDHJHIFovExk+G4/N7wEwvPFAuRB2SZN2WHPVp5sFHZ2hcom6vB//9YIgCLI1sfffp3wuuTqB3Psv3QYZhvOrSJ75fmPTpGLWrLf5WqL0IngsJUse9zT3NDTZF/GzKd2SUeWyhXsIIvSHHJLE/EWsR9eRUhE11JtdIhrbX+sLSoXdT54xYbF5ZYVDfe40VetUu1mpCLp83Z0RLqLgAGBEt4fqOrXEbqCnmLdIa1PTKYvrexwtPbIemI3g5up/L3WSxRUY6XxNVvA5e/P/hQNZo946v0QB5TI8tuk=
    - secure: ERQRWonb1ZOGDcgTSkZxoHzyGLPrrftyyfQez4tEdUQQikzMk+dwAT8OiLe9slLQ6JqbvKXY8M3mrFD3hlfkIcoZw2plMDhB6ocw0oiD7yKDFGgO3Ff6a9x4gDC2oslDpXxZ3anOyF6M0XyHHJbYy1/XbMdJ6cgLXQoOIYZXxTBmFD/6RKsV0TBKPWCV1eQ+5uuaPeSNpfKoUgohFvFtLflMgDNTyhkoaH0/siK+ThUi745ycnAoclaIf60hea6mN8fddnxKkyckbi2WfXkKtXrl718q6exK5Ba8JXWJiLL+VtT4FB3KTZTKP46eMHRL/LWXd58lLdRyTn1W1qST95tn8koEJgDBXPG2WUPByMCyoEiYCLn9wp+AlTJqUEVdiB4C6ajvNTF5k6wmXvP3AWjbkLphKxCqLmCQ3o0rkwjNC4KB0cVeLBZYEfQMq0wq/hnlixrgYT81/hd/OxcS79zQPa7eblOsBNO3U7goi4CKjOqPyWqAK3Wi3JwyG+0B8YBiSakMwdZrz9Rin0DdmGOyQgNz972OwaFyng5B6EdYr2YkS6iRckPsCAT8OXPtVGl7kXC50zTiUY2wb4SLIbwZAJxV9VhGX9Izt7+1X4xUWxNbwDkDOir02Hg6i6ZcAqykf2B7jJKnINIUGzPjmadC1Gf7WiOTZzxUC0Je2Ro=
